const data = [
  {
    id: 1,
    name: "Pasta with Tomato Sauce",
    type: "lunch",
    prep: 15,
    cook: 20,
    serving: 2,
    ingredients: [
      "Pasta",
      "Tomato sauce",
      "Garlic",
      "Onion",
      "Olive oil",
      "Basil leaves",
      "Parmesan cheese",
    ],
    author: "chef_cuisine",
    date: "12:30 pm.",
    details: [
      "Boil the pasta in a large pot of salted water until al dente, then drain.",
      "In a separate pan, heat olive oil and sauté garlic and onion until fragrant.",
      "Add tomato sauce and basil leaves, simmer for 10 minutes.",
      "Toss the cooked pasta in the tomato sauce and serve with grated Parmesan cheese.",
    ],
    options: ["vegetarian", "gluten-free"],
    level: "medium",
    video: "https://youtu.be/Svk1SwdL1eg?si=5a12QkUC1fYjF7jv",
    image: ["https://images.food52.com/-jxHBleXv6CRl_mIZfO_bUzeK_Q=/660x440/filters:format(webp)/52096452-f9c1-49e9-9e76-46c694bee2ba--2020-1124_steak-frites_3x2_rocky-luten_032.jpg", "https://i.pinimg.com/564x/b1/09/13/b109139e11d81e23dc2fcc02d8c465d3.jpg"],
  },
  {
    id: 2,
    name: "Grilled Chicken Salad",
    type: "lunch",
    prep: 15,
    cook: 15,
    serving: 2,
    ingredients: [
      "Chicken breasts",
      "Lettuce",
      "Tomatoes",
      "Cucumbers",
      "Red onions",
      "Olive oil",
      "Lemon juice",
      "Salt",
      "Pepper",
    ],
    author: "healthy_eating",
    date: "01:15 pm.",
    details: [
      "Season chicken breasts with salt and pepper.",
      "Grill the chicken on medium-high heat until cooked through, about 6-7 minutes per side.",
      "Toss lettuce, tomatoes, cucumbers, and red onions in a large bowl.",
      "Slice grilled chicken and place on top of the salad.",
      "Drizzle with olive oil and lemon juice, season with salt and pepper, and serve.",
    ],
    options: ["low-carb", "gluten-free"],
    level: "easy",
    video: "https://youtu.be/v1VUg6r4yFA?si=-uqdaaCdllrPjEwm",
    image: ["https://www.eatwell101.com/wp-content/uploads/2023/06/heathy-grilled-chicken-salad.jpg", "https://cdn.healthyrecipes101.com/recipes/images/chickens/grilled-chicken-salad-dressing-claxsgf9l0018321b6egb53br.webp?w=1080&q=80"],
  },
  {
    id: 3,
    name: "Vegetable Stir-Fry",
    type: "dinner",
    prep: 15,
    cook: 10,
    serving: 4,
    ingredients: [
      "Mixed vegetables",
      "Tofu",
      "Soy sauce",
      "Sesame oil",
      "Garlic",
      "Ginger",
      "Rice",
    ],
    author: "vegan_delights",
    date: "07:00 pm.",
    details: [
      "Heat sesame oil in a pan and add minced garlic and ginger.",
      "Add tofu and stir-fry until it's golden brown.",
      "Add mixed vegetables and stir-fry for 5-7 minutes.",
      "Pour in soy sauce and cook for an additional 2 minutes.",
      "Serve over cooked rice.",
    ],
    options: ["vegan", "gluten-free"],
    level: "medium",
    video: "https://youtu.be/h8IXBipqYgs?si=Bw6UScJwe25rBxrh",
    image: ["https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/sachas_stir-fry_17077_16x9.jpg", "https://therecipecritic.com/wp-content/uploads/2019/08/vegetable_stir_fry.jpg"],
  },
];

exports.data = data;
