const data = [
  {
    id: 1,
    name: "Pasta with Tomato Sauce",
    type: "lunch",
    prep: 15,
    cook: 20,
    serving: 2,
    ingredients: [
      "Pasta",
      "Tomato sauce",
      "Garlic",
      "Onion",
      "Olive oil",
      "Basil leaves",
      "Parmesan cheese",
    ],
    author: "chef_cuisine",
    date: "12:30 pm.",
    details: [
      "Boil the pasta in a large pot of salted water until al dente, then drain.",
      "In a separate pan, heat olive oil and sauté garlic and onion until fragrant.",
      "Add tomato sauce and basil leaves, simmer for 10 minutes.",
      "Toss the cooked pasta in the tomato sauce and serve with grated Parmesan cheese.",
    ],
    options: ["vegetarian", "gluten-free"],
    level: "medium",
    video: "https://youtu.be/Svk1SwdL1eg?si=5a12QkUC1fYjF7jv",
    image: [
      "https://images.food52.com/-jxHBleXv6CRl_mIZfO_bUzeK_Q=/660x440/filters:format(webp)/52096452-f9c1-49e9-9e76-46c694bee2ba--2020-1124_steak-frites_3x2_rocky-luten_032.jpg",
      "https://i.pinimg.com/564x/b1/09/13/b109139e11d81e23dc2fcc02d8c465d3.jpg",
    ],
  },
  {
    id: 2,
    name: "Grilled Chicken Salad",
    type: "lunch",
    prep: 15,
    cook: 15,
    serving: 2,
    ingredients: [
      "Chicken breasts",
      "Lettuce",
      "Tomatoes",
      "Cucumbers",
      "Red onions",
      "Olive oil",
      "Lemon juice",
      "Salt",
      "Pepper",
    ],
    author: "healthy_eating",
    date: "01:15 pm.",
    details: [
      "Season chicken breasts with salt and pepper.",
      "Grill the chicken on medium-high heat until cooked through, about 6-7 minutes per side.",
      "Toss lettuce, tomatoes, cucumbers, and red onions in a large bowl.",
      "Slice grilled chicken and place on top of the salad.",
      "Drizzle with olive oil and lemon juice, season with salt and pepper, and serve.",
    ],
    options: ["low-carb", "gluten-free"],
    level: "easy",
    video: "https://youtu.be/v1VUg6r4yFA?si=-uqdaaCdllrPjEwm",
    image: [
      "https://www.eatwell101.com/wp-content/uploads/2023/06/heathy-grilled-chicken-salad.jpg",
      "https://cdn.healthyrecipes101.com/recipes/images/chickens/grilled-chicken-salad-dressing-claxsgf9l0018321b6egb53br.webp?w=1080&q=80",
    ],
  },
  {
    id: 3,
    name: "Vegetable Stir-Fry",
    type: "dinner",
    prep: 15,
    cook: 10,
    serving: 4,
    ingredients: [
      "Mixed vegetables",
      "Tofu",
      "Soy sauce",
      "Sesame oil",
      "Garlic",
      "Ginger",
      "Rice",
    ],
    author: "vegan_delights",
    date: "07:00 pm.",
    details: [
      "Heat sesame oil in a pan and add minced garlic and ginger.",
      "Add tofu and stir-fry until it's golden brown.",
      "Add mixed vegetables and stir-fry for 5-7 minutes.",
      "Pour in soy sauce and cook for an additional 2 minutes.",
      "Serve over cooked rice.",
    ],
    options: ["vegan", "gluten-free"],
    level: "medium",
    video: "https://youtu.be/h8IXBipqYgs?si=Bw6UScJwe25rBxrh",
    image: [
      "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/sachas_stir-fry_17077_16x9.jpg",
      "https://therecipecritic.com/wp-content/uploads/2019/08/vegetable_stir_fry.jpg",
    ],
  },
  {
    id: 4,
    name: "Spaghetti Carbonara",
    type: "dinner",
    prep: 10,
    cook: 15,
    serving: 2,
    ingredients: [
      "200g spaghetti",
      "100g pancetta or guanciale",
      "2 large eggs",
      "50g Pecorino Romano cheese",
      "50g Parmesan cheese",
      "2 cloves garlic",
      "Salt and black pepper to taste",
    ],
    author: "italian_cuisine",
    date: "08:00 pm.",
    details: [
      "Cook the spaghetti according to package instructions until al dente.",
      "In a separate pan, cook pancetta or guanciale until crispy. Remove excess fat.",
      "In a bowl, whisk eggs, grated Pecorino Romano, grated Parmesan, and minced garlic.",
      "Drain cooked spaghetti and toss it in the egg and cheese mixture until creamy.",
      "Add the cooked pancetta or guanciale, season with salt and black pepper, and serve immediately.",
    ],
    options: ["gluten-free option available"],
    level: "easy",
    video: "https://www.youtube.com/watch?v=2A3nVIeCjZw",
    image: [
      "https://static01.nyt.com/images/2021/02/14/dining/carbonara-horizontal/carbonara-horizontal-master768-v2.jpg?w=1280&q=75",
      "https://img.bestrecipes.com.au/FRcyhV9c/w643-h428-cfill-q90/br/2020/07/spaghetti-carbonara-959371-1.jpg",
    ],
  },
  {
    id: 5,
    name: "Chicken Alfredo",
    type: "dinner",
    prep: 15,
    cook: 20,
    serving: 4,
    ingredients: [
      "8 oz fettuccine pasta",
      "2 boneless, skinless chicken breasts",
      "2 tablespoons olive oil",
      "2 cloves garlic, minced",
      "1 cup heavy cream",
      "1 cup grated Parmesan cheese",
      "Salt and black pepper to taste",
      "Fresh parsley for garnish",
    ],
    author: "italian_delights",
    date: "07:30 pm.",
    details: [
      "Cook fettuccine pasta according to package instructions until al dente.",
      "Season chicken breasts with salt and pepper, then sauté in olive oil until cooked through. Remove and slice.",
      "In the same pan, add minced garlic and cook briefly, then add heavy cream and Parmesan cheese. Stir until creamy.",
      "Add cooked fettuccine to the sauce and toss to coat.",
      "Top with sliced chicken and garnish with fresh parsley. Serve hot.",
    ],
    options: ["gluten-free option available"],
    level: "medium",
    video: "https://www.youtube.com/watch?v=HB5T3q3pZKw",
    image: [
      "https://hips.hearstapps.com/hmg-prod/images/delish-221130-perfect-chicken-alfredo-0689-eb-1670449996.jpg?crop=1.00xw:0.737xh;0,0.134xh&resize=980:*",
      "https://thecozycook.com/wp-content/uploads/2022/08/Chicken-Alfredo-Pasta-1.jpg",
    ],
  },
];

exports.data = data;
